trigger:
- main

jobs:

- job: run
  timeoutInMinutes: 10

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'

  - script: |
      pwd
      ls -la
      pip install DrissionPage
      docker compose up -d
      ls la /app/user_data
      ss -tlnp | grep 9222
      lsof -i :9222
      docker exec chrome ps aux | grep chrome
      docker exec chrome curl http://127.0.0.1:9222/json
      # python test.py
      sleep 5
    displayName: 'Run'

    

