trigger:
- main

jobs:

- job: run
  timeoutInMinutes: 10

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'

  - script: |
      pwd
      ls -la
      pip install DrissionPage
      docker compose up -d
      ls -la data
      ss -tlnp
      docker logs frpc
      docker exec chrome bash -c "ps -ef"
      # python test.py
      sleep 5
    displayName: 'Run'

    

