services:
  chrome:
    image: lscr.io/linuxserver/chrome:latest
    container_name: chrome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=/app/user_data --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
    # volumes:
    #   - ./data/chrome/config:/config
    # ports:
    #   - 3000:3000
    #   - 3001:3001
    shm_size: "2gb"
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped

  frpc:
    image: fatedier/frpc:v0.65.0
    container_name: frpc
    restart: unless-stopped
    volumes:
      - ./data/frpc/frpc.toml:/etc/frp/frpc.toml
      - ./data/frpc/logs:/var/log
    command: ["-c", "/etc/frp/frpc.toml"]
    depends_on:
      - chrome
    extra_hosts:
      - "host.docker.internal:host-gateway"